version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80"
    links:
        - project1
        - project2
        - project3


  project1:
    build: ./project
    volumes:
        - ./main1.bundle.js:/usr/src/manage-project/public/dist/main.bundle.js
    expose:
        - "8080"
    links:
        - mongo



  project2:
      image: compose_project1:latest
      volumes:
          - ./main2.bundle.js:/usr/src/manage-project/public/dist/main.bundle.js
      expose:
          - "8080"
      links:
          - mongo

  project3:
      image: compose_project1:latest
      volumes:
          - ./main3.bundle.js:/usr/src/manage-project/public/dist/main.bundle.js
      expose:
          - "8080"
      links:
          - mongo

  mongo:
      image: mongo:latest
      volumes:
          - ./mongo:/data/db
      expose:
          - "27017"
